### ISSUE TITLE
exec: "code": Executable file not found in $PATH

### ISSUE THREAD

**Issue by BenoitFreslon** [PhaserEditor2D/PhaserEditor2D-v3#182] opened 2022-01-18 10:22 UTC
## Version

* Phaser Editor 2D Version:
Phaser Editor All-in-one 
3.32 OSX

* Operating System:

OSX 12.1

## Description

When I click on "Open in Visual Studio Code" I got this error message : `exec: "code": Executable file not found in $PATH`
I also installed the VS Code command in my terminal with "Shell command" plugin from VSCODE.

The "code" command opens VS Code.

**Comment by PhaserEditor2D** [comment] 2022-03-17 09:43
Hi!

I tested it and it works for me.

I used the method described below for installing `code`:

https://code.visualstudio.com/docs/setup/mac#_launching-from-the-command-line

**Comment by gitteers** [comment] 2022-03-28 15:37
same here.
"code" run in the terminal.
but when I click "Open in Visual Studio Code" menu,  exec: "code": Executable file not found in $PATH error occured

**Comment by PhaserEditor2D** [comment] 2022-03-28 15:41
> same here.
> "code" run in the terminal is OK
> but when I click "Open in Visual Studio Code" menu, exec: "code": Executable file not found in $PATH error occured

Did you restarted Phaser Editor 2D? Fully closed it?

**Comment by PhaserEditor2D** [comment] 2022-03-28 15:42
<img width="566" alt="Screen Shot 2022-03-28 at 11 41 47 AM" src="https://user-images.githubusercontent.com/12187299/160435840-e37f1e53-217d-417a-8950-1957f2e44d9b.png">

Nice! I can reproduce it in All in One now! Let's work on it.

**Comment by PhaserEditor2D** [comment] 2022-03-29 14:38
It looks like a problem of Node and the `spawn` function.
However, I have a solution here. You can set the `-external-editor-command` to point to your VS Code installation.
I tested it and it works. So, please, follow this steps:

- Create a `flags.txt` file in your `/Users/<your user>/.phasereditor2d/` folder.

- Write this content to the file:
```
-external-editor-command
/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code "$LOC"
```
 - Restart the editor and press ⌘⌥U

 Here I attach the `flags.txt` file:  [flags.txt](https://github.com/PhaserEditor2D/PhaserEditor2D-v3/files/8372439/flags.txt)

**Comment by PhaserEditor2D** [comment] 2022-04-05 04:16
I close this. If it doesn't work for you. Please, open it again.

**Closed by PhaserEditor2D** 2022-04-05 04:16 UTC
