### ISSUE TITLE
Ability to set default editor for opening code files

### ISSUE THREAD

**Issue by APWhiteside** [PhaserEditor2D/PhaserEditor2D-v3#273] opened 2023-04-06 15:03 UTC
A way to set it so code files open in VS code when clicked in the "files" panel rather than opening the built in editor. 

Effectively recreating the functionality unity has when you set the external script editor (clicking on a script will open in your set editor rather than say MonoDevelop that unity comes  with)

**Comment by PhaserEditor2D** [comment] 2023-04-07 09:56
A duplicate of #208

**Closed by PhaserEditor2D** 2023-04-07 09:56 UTC
Labels: Enhancement
