### ISSUE TITLE
Creating Project from Template Causes Application to Close [All-in-One edition]

### ISSUE THREAD

**Issue by Bellusterra** [PhaserEditor2D/PhaserEditor2D-v3#146] opened 2021-09-29 00:25 UTC
Downloaded [Phaser Editor 2D All-in-One V3.30](https://updates.phasereditor2d.com/v3.30.0/PhaserEditor2D-allInOne-3.30.0-windows.zip) for Windows 10 from official website. Unzipped and pressed the PhaserEditor2D.exe file. Application opens as expected. New Project and select a project template. Create new folder and Select Folder as project destination and the Application then closes. Trying to reopen Application with the PhaserEditor2D.exe file again results in a blank window showing for a brief amount of time and closing again. The only solution to open Application again is to remove the folder that was created for the project that has the template files copied into it.

**Comment by PhaserEditor2D** [comment] 2021-09-29 13:40
Hi @Bellusterra 

I transferred the issue here.

**Comment by Bellusterra** [comment] 2021-10-01 00:00
It may very well be something I am doing wrong or perhaps changed on my computer to prevent it from working properly as there are no other reports of other people having this same issue. I downloaded the file above and had the same results. here is the output from terminal:
`Starting Phaser Editor 2D Core server
Saved port: 2153
Spawn: C:/Users/james/Downloads/PhaserEditor2D-allInOne-3.30.0-windows-fix-4/PhaserEditor2D/resources/app/server/PhaserEditor2D.exe
[
  '-disable-open-browser',
  '-port',
  '2153',
  '-project',
  'C:/Users/james/Documents/PhaserEditor2D-Projects/PhaserEditor-Projects/test'
]
Process ID: 23760`

**Comment by PhaserEditor2D** [comment] 2021-10-01 02:01
Hi @Bellusterra 

There is at least another user with the same problem. You are not along :)

Your GitHub account shows that you are in Japan. Is your OS in the Japanese language? The other user with the same problem also is using a Windows with the Asian language.

Yet I don't know what's causing the problem. Can you check please if your antivirus is stopping the server's `PhaserEditor2D.exe` file? It is located in `/PhaserEditor2D/resources/app/server/`.

**Comment by Bellusterra** [comment] 2021-10-01 02:27
I'm using Windows 10 in English, Windows will initially prompt that application is from unknown publisher, but I run press run anyway for `/PhaserEditor2D/resources/app/server/`. Initially everything runs as expected the application opens and I have options to select template to download. only after installing the template and the application attempting to open those files does it fail. As far as antivirus I do not see anything in the windows antivirus settings where it is being blocked or logged as a threat.

**Comment by PhaserEditor2D** [comment] 2021-10-01 08:16
It stops working at the time it tries to run the server executable. The window is blank because it is waiting for the server's response. Please, in the meantime can you use Phaser Editor 2D Core? I should add more debugging info to the all-in-one distribution for finding what's happening. Thanks!

**Comment by Bellusterra** [comment] 2021-10-03 13:16
Oh I see, Thank you for the explanation. I happy test and send you whatever information that you need.

**Comment by Bellusterra** [comment] 2021-10-04 03:51
Did a fresh install of Windows 10, made sure to accept all firewall and network permissions when asked. Neither PhaserEditor2D from the allinOne package or the one from the core package open after importing a new template.

**Comment by PhaserEditor2D** [comment] 2021-10-04 11:28
Hi!

Thanks so much. I will be back to office soon. 
Arian.

**Comment by PhaserEditor2D** [comment] 2021-10-04 15:24
Hi @Bellusterra 

When you run Phaser Editor 2D Core, does it print any error or info? You should run it like this in the CMD:

```
PhaserEditor2D.exe -project path/to/project
```

**Comment by Bellusterra** [comment] 2021-10-05 01:39
okay got it working, the result from your above command was:
 
`C:\Users\James Keller\Downloads\PhaserEditor2D-core-3.30.0-windows\PhaserEditor2D>PhaserEditor2D.exe -project C:\\Users\\James Keller\\Documents\\PhaserEditor2D\\new-project
Phaser Editor 2D - v3.30.0
=> Running in Free mode (only 70 files per project allowed)
=> Purchase a license: https://gum.co/phasereditor
2021/10/04 18:30:04 User plugins: C:\Users\James Keller/.phasereditor2d/plugins
2021/10/04 18:30:04 Loading project at directory 'C:\Users\James' does not exists`

It's possible the space in my name within the file location was the problem after moving the project file to the root folder did everything open as expected:

`C:\Users\James Keller\Downloads\PhaserEditor2D-core-3.30.0-windows\PhaserEditor2D>PhaserEditor2D.exe -project C:\\new-project
Phaser Editor 2D - v3.30.0
=> Running in Free mode (only 70 files per project allowed)
=> Purchase a license: https://gum.co/phasereditor
2021/10/04 18:31:22 User plugins: C:\Users\James Keller/.phasereditor2d/plugins
2021/10/04 18:31:22 Loading project at C:\new-project
2021/10/04 18:31:22 Listening at http://127.0.0.1:1959/editor
Play IDE online : https://play.phasereditor2d.com/
Documentation   : https://help.phasereditor2d.com/v3
File bugs/ideas : https://github.com/PhaserEditor2D/PhaserEditor2D-v3/
Keep in contact : https://twitter.com/PhaserEditor2D
=> Open the web browser at http://127.0.0.1:1959/editor`

If not the space in the name I do not know the cause. fresh install of windows 10 with all things set as default not change in file or folder permissions. Hope this helps. the other people with this problem.

**Comment by Bellusterra** [comment] 2021-10-05 01:50
Oh looks like a spoke to soon... still not opening correctly. By moving the project to the new location the program opened, but when starting over and creating the folder in the root as I mentioned I run into the same problem as before.

**Comment by PhaserEditor2D** [comment] 2021-12-24 17:22
Hi @Bellusterra 

Please, can you test this issue with the latest version 3.31.2 of the allInOne?

**Comment by Bellusterra** [comment] 2022-01-04 02:36
I'm able to add and remove images and save properly so that seems to be fixed, although the application will still close out when creating a project and requires opening from the command line to use.

**Comment by PhaserEditor2D** [comment] 2022-01-04 02:46
Hi. Thanks. Another user is getting the same error when creating a new project. Yet I can't reproduce the error.

**Comment by PhaserEditor2D** [comment] 2022-01-05 11:59
Hi @Bellusterra 

Please, if you can check this version: https://updates.phasereditor2d.com/v3.31.2-next/PhaserEditor2D-allInOne-3.31.2-next-windows-20220105.zip

It uses the latest electron.

**Comment by Bellusterra** [comment] 2022-01-06 00:42
Yes, that does appear to fix it! It opens now and stays open!

**Comment by PhaserEditor2D** [comment] 2022-01-06 02:11
> Yes, that does appear to fix it! It opens now and stays open!

God! Finally! Let's see what the other users with the same problem say.

Thanks!

**Closed** 2022-01-06 02:36 UTC
